### PR TITLE
Using new webjars

### PR DESCRIPTION
**Pull request by ZheSun88**
rename repository id;
remove HtmlImport from component demo.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/47)

### CODE REVIEW

**Comment by SomeoneToIgnore** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/47)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/47#-L4_htk4ts5R5YAVaX_a:-L4_htk4ts5R5YAVaX_b:b-o6b4t8) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/f46b7273427bdf9e13788a8a78aef539025b66c4/src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java#L39)):*
> public class ComboBoxView extends DemoView {

`Lumo` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/47)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java, line 39 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/47#-L4_htk4ts5R5YAVaX_a:-L4_i5CWWUPIaip_SnGz:b-cg5i9t) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/f46b7273427bdf9e13788a8a78aef539025b66c4/src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java#L39)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public class ComboBoxView extends DemoView {

`Lumo` ?
</blockquote></details>

lumo will comes from the `DemoView`, so we dont need to add this to the individual component here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/47)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-combo-box-flow/47)*

**Pull request merged**
