### PR TITLE
Add ComponentTemplateRenderer support for ComboBox

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Due to the nature of the `ComponentTemplateRenderer`, the data sent to the client-side component needs to be processed only after the component has been attached. That caused several changes inside the server-side component.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/38)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 177 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2ZxrgFPgA45BgZ_B4x:-L2ZxrgFPgA45BgZ_B4y:b-urlzli) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L177)):*
> if (rendererRegistration != null) {
>             rendererRegistration.remove();
>             rendererRegistration = null;
>         }
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         if (componentRendererRegistration != null) {
>             componentRendererRegistration.remove();
>             componentRendererRegistration = null;
>         }
</details>
>  

can be extracted as a separate method to decrease lines of code here.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 194 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2Zy70-YNcVFez7EPSV:-L2Zy70-YNcVFez7EPSW:b-qzwgd8) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L194)):*
>  Map<String, ValueProvider<T, ?>> valueProviders = renderer
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>                     .getValueProviders();
>             valueProviders.forEach((property, provider) -> json.put(property,
>                     JsonSerializer.toJson(provider.apply(item))));
>         }
</details>

lambda which has inside it `forEach` with lambda.
Would be good to refactor this for better readability.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 206 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2ZzkIIo5gRbGE2LxvZ:-L2ZzkIIo5gRbGE2Lxv_:belrbgi) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L206)):*
> itemsFromDataProvider = dataProvider.fetch(new Query<>())
>                 .collect(Collectors.toList());

So this code makes useless the data provider concept for this component since it fetches all the data from it and stores this data in memory.
I don't know whether the previous state of code supported lazy data providers but this change definitely nullify lazy data provider usage.
Not sure whether this is OK for now or not.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 254 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2_-yEj_Dcb7IuRV1Q4:-L2_-yEj_Dcb7IuRV1Q5:bmzrlg9) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L254)):*
> setFilteredItems(generateJson(temporaryFilteredItems.stream()));
>             temporaryFilteredItems = null;

Does it make sense to move `temporaryFilteredItems = null` into `setFilteredItems();`  method called above ?

---

*[src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2_0yeym_7PzGAXAEx0:-L2_0yez7me3uRxGbLuK:b-vqaudw) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java#L68)):*
> if ("bar".equals(comboBox.getValue())) {
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>                         comboBox.setValue("foo");
>                     } else {
>                         comboBox.setValue("bar");
>                     }
</details>

Can be rewritten without a block with ternary operator inside `setValue()` .
Would be more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 177 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2ZxrgFPgA45BgZ_B4x:-L2diRuM_XYft6k7fASs:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L177)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if (rendererRegistration != null) {
>             rendererRegistration.remove();
>             rendererRegistration = null;
>         }
>  
>         if (componentRendererRegistration != null) {
>             componentRendererRegistration.remove();
>             componentRendererRegistration = null;
>         }
>  

can be extracted as a separate method to decrease lines of code here.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 194 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2Zy70-YNcVFez7EPSV:-L2eACekJeC6T8U-tw-f:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L194)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  Map<String, ValueProvider<T, ?>> valueProviders = renderer
>                     .getValueProviders();
>             valueProviders.forEach((property, provider) -> json.put(property,
>                     JsonSerializer.toJson(provider.apply(item))));
>         }

lambda which has inside it `forEach` with lambda.
Would be good to refactor this for better readability.
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 206 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2ZzkIIo5gRbGE2LxvZ:-L2eAGT9kxJRKr15tDci:b-b9w9kc) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L206)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> itemsFromDataProvider = dataProvider.fetch(new Query<>())
>                 .collect(Collectors.toList());

So this code makes useless the data provider concept for this component since it fetches all the data from it and stores this data in memory.
I don't know whether the previous state of code supported lazy data providers but this change definitely nullify lazy data provider usage.
Not sure whether this is OK for now or not.
</blockquote></details>

As I've got it from discussion on daily, this is fine by now.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 254 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2_-yEj_Dcb7IuRV1Q4:-L2eAKUdwGDoR69fUIbl:b-mrq7bf) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L254)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> setFilteredItems(generateJson(temporaryFilteredItems.stream()));
>             temporaryFilteredItems = null;

Does it make sense to move `temporaryFilteredItems = null` into `setFilteredItems();`  method called above ?
</blockquote></details>

`setFilteredItems` belongs to a different class and `temporaryFilteredItems` belongs to this class, so you cannot really make the change proposed without breaking the encapsulation.

I have no idea how to make the code better without rewriting half of the class, so I propose to leave it as is.

---

*[src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java, line 68 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-L2_0yeym_7PzGAXAEx0:-L2eBpGvrcSpS7YddUpP:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/bee62c4bf18850d99438de0dea2c9854459afcc6/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxPage.java#L68)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> if ("bar".equals(comboBox.getValue())) {
>                         comboBox.setValue("foo");
>                     } else {
>                         comboBox.setValue("bar");
>                     }

Can be rewritten without a block with ternary operator inside `setValue()` .
Would be more readable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38)*

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38)*

**Comment by denis-anisimov** [comment]
@someonetoignore  You need to mark your own comment as resolved.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-:-L2eDg1Y_jR8javxLGu-:b-sf9fer)*

**Comment by SomeoneToIgnore** [comment]
Ah, thanks.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/38#-:-L2eDrEHzzAYkTHqFdp6:b-5hynej)*

**Pull request merged**
