### PR TITLE
Add support for TemplateRenderers on ComboBox

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/35)

### CODE REVIEW

**Comment by ahie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java, line 187 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/35#-L24fePl_7lGRqGPA-sv:-L24fePl_7lGRqGPA-sw:b4axi0j) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/1a460d694bb454fd9ca4af8da7a52b2f5c81e1ea/src/test/java/com/vaadin/flow/component/combobox/demo/ComboBoxView.java#L187)):*
> ```Java
>     }
> 
>     private void createComboBoxUsingTemplateRenderer() {
> ```

Would be nice to have a demo of number/date renderer being used directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/35)*

**Comment by gilberto-torrezan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/35#-L25SfDvYUAi_SbYztR0:-L25SfDvYUAi_SbYztR1:b-kt3vk) (no related file):*
Do not merge this yet - there is the event support missing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/35)*

**Comment by gilberto-torrezan** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/35#-L25SfDvYUAi_SbYztR0:-L25mT0v-rpSeP-4_TmQ:bvk0znv) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Do not merge this yet - there is the event support missing.
</blockquote></details>

This branch will only build when https://github.com/vaadin/flow/pull/3271 is merged.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 149 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/35#-L24dzA0ZRdvX5v63maU:-L25mWeC4UbpI0orhaFv:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/1a460d694bb454fd9ca4af8da7a52b2f5c81e1ea/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L149)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> must not
`can not` 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/35)*

**Comment by caalador** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-combo-box-flow/35)*

**Pull request merged**
