### PR TITLE
Keep the value before disabling the component

### PR DESCRIPTION
**Pull request by ZheSun88**
Add test case;
Fixes#83.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
What's the reason of the current behavior?
It looks like you have fixed the symptoms. But not the original problem.
If I got it right then previously it worked just fine. What has changed ?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 496 at r1](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-LE8y0Yb3XTyOGa1uBAo:-LE8y0Yb3XTyOGa1uBAp:buj3gvq) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/241dbf8772680e5856ac632060778e7d35f3f7de/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L496)):*
> ```
>         return (getValue(getElement()
>                 .getPropertyRaw(SELECTED_ITEM_PROPERTY_NAME))) == null
> ```

You are using the same value twice. Here to check against `null` and below as a value.
It would be OK if it wasn't so long.
So please extract it as a variable and use the variable instead in the expression.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LE8z1wI1gdTO91t-ag7:b-6k7wht)*

**Comment by ZheSun88** [comment]
The problem, after https://github.com/vaadin/flow/issues/2104 got merge, it has override the `getValue` method, then if we set the component to disabled, the `SELECTED_ITEM` will be null, as the component is disabled. 

what we have expected is setValue("foo"), setEnabled(false), the value you can get from the component is still `foo`. in the fix we have store the value we have set before disable the component and return it when getValue is called. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LE8zkZT6aLpj7y1ncAY:b-q2f9x0)*

**Comment by ZheSun88** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/combobox/ComboBox.java, line 496 at r1](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-LE8y0Yb3XTyOGa1uBAo:-LE91-ir6bO6JDFxeGJz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-combo-box-flow/blob/241dbf8772680e5856ac632060778e7d35f3f7de/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java#L496)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>         return (getValue(getElement()
>                 .getPropertyRaw(SELECTED_ITEM_PROPERTY_NAME))) == null
> ```

You are using the same value twice. Here to check against `null` and below as a value.
It would be OK if it wasn't so long.
So please extract it as a variable and use the variable instead in the expression.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84)*

**Comment by denis-anisimov** [comment]
> SELECTED_ITEM

What's that ?

>The problem, after vaadin/flow#2104 got merge, it has override the getValue method
I don't see changes in `ComboBox` for 3 weeks.

#2104 is the main big issue. Which PR you are referring too ?

Could you please give more accurate comment ?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LE9Epqc6Vqe5vr-lr3F:b-9dcapc)*

**Comment by denis-anisimov** [comment]
In which way `setEnabled` influence at all on the functionality ?

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LE9FUCR7cvNqLCNcjIJ:b-15jc6y)*

**Comment by ZheSun88** [comment]
sorry, it was this one.. https://github.com/vaadin/vaadin-combo-box-flow/commit/432c9e6d83eda861d8cc69a45dedaed3db633f14 

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LE9GD1eA0JpK2BGB9-s:bu0t9je)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-LE9GXs2BF9IhRyeJfzN:-LE9GXs2BF9IhRyeJfzO:b-efvbqe) (no related file):*
no merge until we solve the discussion 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84)*

**Comment by denis-anisimov** [comment]
OK.

And the last thing : why does `getElement().getPropertyRaw(SELECTED_ITEM_PROPERTY_NAME)` return `null` if element is disabled ?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LE9IAmd8ZTSSaZ_fPP2:b-s6qxpt)*

**Comment by ZheSun88** [comment]
Okay, finally, we have figured out the problem and i am going to add more test cases for testing the fixes. Thanks Denis

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LE9wFwa1UgBzYqiwjFH:b-xhln5p)*

**Comment by ZheSun88** [comment]
Now, i think i can explain the root reason for causing this problem, during the `setEnabled(false)` call, we remove everything inside the keyMapper, together with the value we want. And our `assert` runs before the `runBeforeClientResponse` block, which bring the removed items back. 

The reason why we move the `keyMapper.removeAll();` into the `runBeforeClientResponse` block is just the test case shows. otherwise the test will fail on getValue equals to null again

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LEADcUp7RJuf5G0cz31:b-tub1cc)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-combo-box-flow/84#-:-LEDanjH7LhxrBQ0Y41f:bnfp4nl)*

**Pull request merged**
